Script started on Wed 01 Mar 2023 11:48:11 AM PST
]0;rgate@bondi:~/hw4[rgate@bondi ~/hw4]$ make
gcc -std=c11 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -std=c11 -Wall -c FileIO.c -o FileIO.o
gcc -std=c11 -Wall -c Image.c -o Image.o
gcc -std=c11 -Wall -c Test.c -o Test.o 
gcc -std=c11 -Wall -c DIPs.c -o DIPs.o
gcc -std=c11 -Wall -c Advanced.c -o Advanced.o
ar rc libfilter.a Advanced.o DIPs.o
ranlib libfilter.a
gcc -std=c11 -Wall -g PhotoLab.o FileIO.o Image.o Test.o -L. -lfilter -o PhotoLab -lm
gcc -std=c11 -Wall -c -DDEBUG  PhotoLab.c -o PhotoLab_DEBUG.o
gcc -std=c11 -Wall -c -DDEBUG  Test.c -o Test_DEBUG.o 
gcc -std=c11 -Wall -DDEBUG  PhotoLab_DEBUG.o Test_DEBUG.o FileIO.o Image.o -L. -lfilter -o PhotoLabTest -lm
]0;rgate@bondi:~/hw4[rgate@bondi ~/hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image horizontally
 9: Mirror an image horizontally
10: Add border to an image
11: Normalize an image
12: Posterize an image
13: Rotate and zoom an image
14: Add Motion Blur to an image
15: Crop an Image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test All Functions
20: Exit
Please make your choice: 19
PhotoLab: Image.c:46: SetPixelR: Assertion `y < ImageHeight(image)' failed.
Abort
]0;rgate@bondi:~/hw4[rgate@bondi ~/hw4]$ ./PhotoLab[22Gmake[K~eecs22/bin/turnin.sh[22Gcd ..[K[22Gexit[Kmake clean[22Gvalgrind --leak-check=full PhotoLabTestll [1@.[1@/
==32741== Memcheck, a memory error detector
==32741== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32741== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==32741== Command: ./PhotoLabTest
==32741== 
Black and White tested!

Negative tested!

Color Filter tested!

PhotoLabTest: Image.c:46: SetPixelR: Assertion `y < ImageHeight(image)' failed.
==32741== 
==32741== Process terminating with default action of signal 6 (SIGABRT)
==32741==    at 0x516F387: raise (raise.c:55)
==32741==    by 0x5170A77: abort (abort.c:90)
==32741==    by 0x51681A5: __assert_fail_base (assert.c:92)
==32741==    by 0x5168251: __assert_fail (assert.c:101)
==32741==    by 0x401CCD: SetPixelR (in /users/ugrad/rgate/hw4/PhotoLabTest)
==32741==    by 0x403BBC: Edge (in /users/ugrad/rgate/hw4/PhotoLabTest)
==32741==    by 0x400E9C: AutoTest (in /users/ugrad/rgate/hw4/PhotoLabTest)
==32741==    by 0x400B75: main (in /users/ugrad/rgate/hw4/PhotoLabTest)
==32741== 
==32741== HEAP SUMMARY:
==32741==     in use at exit: 388,832 bytes in 4 blocks
==32741==   total heap usage: 25 allocs, 21 frees, 1,559,485 bytes allocated
==32741== 
==32741== LEAK SUMMARY:
==32741==    definitely lost: 0 bytes in 0 blocks
==32741==    indirectly lost: 0 bytes in 0 blocks
==32741==      possibly lost: 0 bytes in 0 blocks
==32741==    still reachable: 388,832 bytes in 4 blocks
==32741==         suppressed: 0 bytes in 0 blocks
==32741== Reachable blocks (those to which a pointer was found) are not shown.
==32741== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==32741== 
==32741== For lists of detected and suppressed errors, rerun with: -s
==32741== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Abort
]0;rgate@bondi:~/hw4[rgate@bondi ~/hw4]$ make clean
rm -f *.o *.jpg  edge.ppm normalize.ppm posterize.ppm rotate.ppm negative.ppm blackNWhite.ppm crop.ppm colorfilter.ppm addborder.ppm brightnessandcontrast.ppm motionblur.ppm edge.ppm shuffle.ppm hflip.ppm hmirror.ppm  libfilter.a libFileIO.a
rm -f PhotoLab
rm -f PhotoLabTest
]0;rgate@bondi:~/hw4[rgate@bondi ~/hw4]$ exit
exit

Script done on Wed 01 Mar 2023 11:49:12 AM PST
