Script started on Wed 01 Feb 2023 11:02:58 AM PST
]0;rgate@bondi:~/hw2[rgate@bondi ~/hw2]$ ~eecs22/bin/turnin.sh[22Gcd ..[K[22Gls[Kmv typescript PhotoLab.script[22Gexit[K./PhotoLab[22G[31@gcc PhotoLab.c -std=c11 -Wall -o [63G[22G[31P./[32G[22Gexit[K./PhotoLab[22G[31@gcc PhotoLab.c -std=c11 -Wall -o [63G
]0;rgate@bondi:~/hw2[rgate@bondi ~/hw2]$ gcc PhotoLab.c -std=c11 -Wall -o PhotoLab[22G~eecs22/bin/turnin.sh[K[22Gcd ..[K[22Gls[Kmv typescript PhotoLab.script[22Gexit[K./PhotoLab

----------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black &  White
4: Make a negative of an image
5: Color Filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image horizontally
10: Add border to an image
11: Test all Functions
12: Exit
please make your choice: 1

Please input the file name to load: Engineering
Engineering.ppm was read successfully!

----------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black &  White
4: Make a negative of an image
5: Color Filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image horizontally
10: Add border to an image
11: Test all Functions
12: Exit
please make your choice: ` 11
Engineering.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

Engineering.ppm was read successfully!
colorfilter.ppm was saved successfully. 
colorfilter.jpg was stored for viewing. 
Color Filter tested!

Engineering.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge Detection tested!

Engineering.ppm was read successfully!
hmirror.ppm was saved successfully. 
hmirror.jpg was stored for viewing. 
HMirror tested!

Engineering.ppm was read successfully!

Black and White operation is done!bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black & White tested!

Engineering.ppm was read successfully!
hflip.ppm was saved successfully. 
hflip.jpg was stored for viewing. 
HFlip tested!

Engineering.ppm was read successfully!
shuffle.ppm was saved successfully. 
shuffle.jpg was stored for viewing. 
Shuffle tested!


----------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black &  White
4: Make a negative of an image
5: Color Filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image horizontally
10: Add border to an image
11: Test all Functions
12: Exit
please make your choice: 12
exiting program
]0;rgate@bondi:~/hw2[rgate@bondi ~/hw2]$ exit
exit

Script done on Wed 01 Feb 2023 11:03:28 AM PST
