Script started on Fri 17 Mar 2023 10:47:35 AM PDT
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ make

gcc -g -ansi -Wall -c -std=c11  FileIO.c -o FileIO.o
gcc -g -ansi -Wall -c -std=c11  DIPs.c -o DIPs.o
gcc -g -ansi -Wall -c -std=c11  Image.c -o Image.o
gcc -g -ansi -Wall -c -std=c11  ImageList.c -o ImageList.o
gcc -g -ansi -Wall -c -std=c11  MovieLab.c -o MovieLab.o -lm
gcc -g -ansi -Wall -c -std=c11  Movie.c -o Movie.o
gcc -g -Wall FileIO.o DIPs.o Image.o ImageList.o MovieLab.o Movie.o -o MovieLab -lm
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./Movuie[K[K[KieLab -h


Usage: MovieLab -i <file> -o <file> -f <framenum> -s <WidthxHeight> [options]
Options:
-bw                   Activate the black and white filter on every movie frame
-hmirror              Activate horizontal mirror on every movie frame
-edge                 Activate the edge filter on every movie frame
-crop <start-end>     Crop the movie frames from <start> to <end>
-fast <factor>        Fast forward the movie by <factor>
-reverse              Reverse the frame order of the input movie
-watermark <file>     Add a watermark from <file> to every movie frame
-spotlight            Spotlight the fade in and fade out
-rotate               Rotate and zoom in/out the input movie
-h                    Display this usage information
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -bw



The movie file Engineering.yuv has been read successfully"BlackNWhite" operation is done!The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -hmirror



The movie file Engineering.yuv has been read successfully"HMirror" operation is done!The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -edge



The movie file Engineering.yuv has been read successfully"Edge" operation is done!The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -fast 3



The movie file Engineering.yuv has been read successfully"Fast" operation is done!The movie file out.yuv has been written successfully!
24 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -crop 10-20



The movie file Engineering.yuv has been read successfully"Crop" operation is done!The movie file out.yuv has been written successfully!
11 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -reverse



The movie file Engineering.yuv has been read successfully"Reverse" operation is done!The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -watermark watermark.ppm



The movie file Engineering.yuv has been read successfullyThe movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270 -spotlight


Segmentation fault
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ valgrind ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -=s[K[K[K-s 480-[Kx270

==6001== Memcheck, a memory error detector
==6001== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==6001== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==6001== Command: ./MovieLab -i Engineering.yuv -o out.yuv -f 70 -s 480x270
==6001== 


The movie file Engineering.yuv has been read successfullyThe movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
==6001== 
==6001== HEAP SUMMARY:
==6001==     in use at exit: 0 bytes in 0 blocks
==6001==   total heap usage: 983 allocs, 983 frees, 81,697,880 bytes allocated
==6001== 
==6001== All heap blocks were freed -- no leaks are possible
==6001== 
==6001== For lists of detected and suppressed errors, rerun with: -s
==6001== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ clean[K[K[K[K[Kmake clean[Kn[K[K[K[K[K[K[K[K[Kmake clean

rm -f *.o MovieLab hmirror.ppm reverse.ppm fast.ppm blacknwhite.ppm edge.ppm spotlight.ppm rotate.ppm crop.ppm watermark.ppm rotate.ppm  out.yuv
]0;rgate@bondi:~/hw5[rgate@bondi ~/hw5]$ exit

exit

Script done on Fri 17 Mar 2023 10:57:06 AM PDT
